DemandTool/Models/Demand.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Reflection;
using System.Web;


namespace DemandTool.MVC.Models
{
    public class Demand
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long Id { get; set; }
        [Required]
        public string DemandNumber { get; set; } // question on why we need demand number
        public DateTime? SubmissionDate { get; set; }
        [DataType(DataType.MultilineText)]
        public string DemandDesc { get; set; }
        public Priority Priority { get; set; }
        public RequestType RequestType { get; set; }
        public RAG RAG { get; set; }
        public ServiceLine ServiceLine { get; set; }
        //public string Customer { get; set; }
        public string CustomerCompany { get; set; }
        public DemandStatus DemandStatus { get; set; }
        public DateTime? CompletionDate { get; set; }
        public string RequesterName { get; set; }
        public bool Blocked { get; set; }
        public string ReasonOfBlockage { get; set; }
        public Phase Phase { get; set; }
        public virtual List<DemandLog> DemandLogs { get; set; }
    }

    public enum Priority { high, medium, low }

    public enum RequestType
    {
        [Display(Name = "BAU Demands")]
        BAUdemands,
        [Display(Name = "BAU Projects")]
        BAUprojects
    }

    public enum RAG { RedColour, AmberColour, GreenColour }

    public enum ServiceLine
    {
        Amelia,
        Automation,

        Rocotics,
        ITSM,
        Analytics,
        Monitoring,
        [Display(Name = "Transformation and on boarding projects")]
        TransformationProject,
        [Display(Name = "Tools and Deployments")]
        EnvironmentsDeployments
    }


    public enum DemandStatus { Completed, Assigned, Rejected, Cancelled, onHold }
    public enum Phase
    {
        InitialReview,
        [Display(Name = "Pre-Assessment Validation")]
        PreAssessmentValidation,
        [Display(Name = "High Level Assessment")]
        HighLevelAssessment,
        [Display(Name = "Business Approval")]
        BusinessApproval,
        [Display(Name = "A waiting Delivery")]
        AwaitingDelivery,
        InDelivery
    }

  
}

DemandTool/Controllers/DemandsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Web.UI;
using System.Web.UI.WebControls;
using DemandTool.MVC.Context;
using DemandTool.MVC.Models;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace DemandTool.MVC.Controllers
{
    [Authorize]
    public class DemandsController : Controller
    {
        private DefaultDBContext db = new DefaultDBContext();

        // GET: Demands
        public ActionResult Index()
        {
            return View(db.Demands.ToList());
        }

        //public ActionResult IndexData()
        //    {

        //    var result = db.Demands.ToList();
        //      //var result2 =  Json(JsonConvert.SerializeObject(result.ToArray()), JsonRequestBehavior.AllowGet);

        //    var serializer = new JavaScriptSerializer();
        //    var serializedResult = serializer.Serialize(result);
        //    return Json (serializedResult);


        //}
        public ActionResult IndexData()
        {
            
            var result = (db.Demands.ToList()).ToArray();
            var result2 =  Json(JsonConvert.SerializeObject(result), JsonRequestBehavior.AllowGet);

            //var serializer = new JavaScriptSerializer();
            //var serializedResult = serializer.Serialize(result);
            return result2;

        }

        // GET: Demands/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Demand demand = db.Demands.Include(d=>d.DemandLogs).ToList().Find(d => d.Id == id);
            if (demand == null)
            {
                return HttpNotFound();
            }
            return View(demand);
        }

        // GET: Demands/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Demands/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Create(Demand demand)
        {
            if (ModelState.IsValid)
            {
                demand.DemandLogs = new List<DemandLog>()
                {
                    new DemandLog()
                    {
                        AssignedTeam = AssignedTeam.ProductMgt,
                        TeamStatus = TeamStatus.Assigned,
                        DemandStatus= demand.DemandStatus,
                        Phase = demand.Phase,
                        Priority = demand.Priority,
                        RAG = demand.RAG,
                        ServiceLine = demand.ServiceLine,
                        UpdatedDate = DateTime.Now
                    }
                };
                db.Demands.Add(demand);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(demand);
        }

        // GET: Demands/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Demand demand = db.Demands.Find(id);
            if (demand == null)
            {
                return HttpNotFound();
            }
            return View(demand);
        }

        // POST: Demands/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]

        public ActionResult Edit(DemandModel demand)
        {
            if (ModelState.IsValid)
            {
                var dbDemand = db.Demands.Include(d=>d.DemandLogs).First(d=>d.Id == demand.Id);
                dbDemand.Priority = demand.Priority;
                dbDemand.RAG = demand.RAG;
                dbDemand.DemandStatus = demand.DemandStatus;
                dbDemand.ServiceLine = demand.ServiceLine;
                dbDemand.Phase = demand.Phase;
                var newDemandLog = new DemandLog()
                {
                    Priority = demand.Priority,
                    RAG = demand.RAG,
                    DemandStatus = demand.DemandStatus,
                    ServiceLine = demand.ServiceLine,
                    Phase = demand.Phase,
                    AssignedTeam = demand.AssignedTeam,
                    TeamStatus = demand.TeamStatus,
                    Comments = demand.Comments,
                    UpdatedDate = DateTime.Now,
                    DemandId = demand.Id
                };
                dbDemand.DemandLogs.Add(newDemandLog);
                db.SaveChanges();
                //TODO:create DemandDTO
                newDemandLog.Demand = null;
                return Json(JsonConvert.SerializeObject(newDemandLog));
            }
            return Json(JsonConvert.SerializeObject(new { errorMsg = "invalid Object" }));
        }

        // GET: Demands/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Demand demand = db.Demands.Find(id);
            if (demand == null)
            {
                return HttpNotFound();
            }
            return View(demand);
        }

        // POST: Demands/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Demand demand = db.Demands.Find(id);
            db.Demands.Remove(demand);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult ExportToExcel()
        {
            // Step 1 - get the data from database
            var data = db.Demands.Select(r => new { r.Id, r.DemandDesc , r.SubmissionDate,r.DemandNumber, r.DemandStatus, r.Priority, r.Phase }).ToList();
   
            


            // instantiate the GridView control from System.Web.UI.WebControls namespace
            // set the data source
            GridView gridview = new GridView();
            gridview.DataSource = data;
            gridview.DataBind();

            // Clear all the content from the current response
            Response.ClearContent();
            Response.Buffer = true;
            // set the header
            Response.AddHeader("content-disposition", "attachment; filename = Demands.xls");
            Response.ContentType = "application/ms-excel";
            Response.Charset = "";
            // create HtmlTextWriter object with StringWriter
            using (StringWriter sw = new StringWriter())
            {
                using (HtmlTextWriter htw = new HtmlTextWriter(sw))
                {
                    // render the GridView to the HtmlTextWriter
                    gridview.RenderControl(htw);
                    // Output the GridView content saved into StringWriter
                    Response.Output.Write(sw.ToString());
                    Response.Flush();
                    Response.End();
                }
            }
            return RedirectToAction("Index");
        }

        public ActionResult ExportHops()
        {

            
            var data = db.DemandLogs.ToList();
            // var data = db.DemandLogs.Select(r => new { r.Id, r.DemandDesc, r.SubmissionDate, r.DemandNumber, r.DemandStatus, r.Priority, r.Phase }).ToList();

            GridView gridview = new GridView();
            gridview.DataSource = data;
            gridview.DataBind();

            Response.ClearContent();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment; filename = Demand logs.xls");
            Response.ContentType = "application/ms-excel";
            Response.Charset = "";
            using (StringWriter sw = new StringWriter())
            {
                using (HtmlTextWriter htw = new HtmlTextWriter(sw))
                {
                    gridview.RenderControl(htw);
                    Response.Output.Write(sw.ToString());
                    Response.Flush();
                    Response.End();
                }
            }
            return RedirectToAction("Index");
        }
    }
}

DemandTool/Views/Demands/Create.cshtml
@model DemandTool.MVC.Models.Demand

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/bootstrap-datepicker.min.css" rel="stylesheet" />
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/bootstrap-datepicker.min.js"></script>
@using (Html.BeginForm())
{
    

    <div class="form-horizontal">
        <h2>Create</h2>

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.DemandNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DemandNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DemandNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SubmissionDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SubmissionDate, new { htmlAttributes = new { @class = "form-control", id = "submission-date" } })
                @Html.ValidationMessageFor(model => model.SubmissionDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DemandDesc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DemandDesc, new { htmlAttributes = new { @class = "form-control", @rows = "5" } })
                @Html.ValidationMessageFor(model => model.DemandDesc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Priority, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Priority, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Priority, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequestType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.RequestType, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RequestType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RAG, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.RAG, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RAG, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ServiceLine, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.ServiceLine, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ServiceLine, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Customer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Customer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Customer, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerCompany, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerCompany, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerCompany, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DemandStatus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.DemandStatus, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DemandStatus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CompletionDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CompletionDate, new { htmlAttributes = new { @class = "form-control", id = "completion-date" } })
                @Html.ValidationMessageFor(model => model.CompletionDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequesterName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RequesterName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RequesterName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Blocked, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Blocked)
                    @Html.ValidationMessageFor(model => model.Blocked, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReasonOfBlockage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReasonOfBlockage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReasonOfBlockage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phase, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Phase, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Phase, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script>
    $('#submission-date').datepicker({
        todayBtn: "linked"
    });
    $('#completion-date').datepicker({
        todayBtn: "linked"
    });

</script>

DemandTool/Views/Demands/Delete.cshtml
@model DemandTool.MVC.Models.Demand

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Demand</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DemandNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DemandNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SubmissionDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubmissionDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DemandDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DemandDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Priority)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Priority)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequestType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RAG)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RAG)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ServiceLine)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ServiceLine)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Customer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerCompany)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerCompany)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.demandStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.demandStatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CompletionDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompletionDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequesterName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequesterName)
        </dd>



        <dt>
            @Html.DisplayNameFor(model => model.Blocked)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Blocked)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReasonOfBlockage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReasonOfBlockage)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DemandTool/Views/Demands/Index.cshtml
@model IEnumerable<DemandTool.MVC.Models.Demand>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<style>
    * {
        font-family: Vodafone;
    }
</style>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
@*<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.min.js"></script>*@
<script src="//cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.2/angular.js"></script>
<link rel="stylesheet" ; href="https://unpkg.com/ng-table@2.0.2/bundles/ng-table.min.css">
<script src="https://unpkg.com/ng-table@2.0.2/bundles/ng-table.min.js"></script>





@*<script src="//cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.2/angular.js"></script>*@

<h2>Demands</h2>


<div class="row justify-content-end">
    <div class="col-md-10">

        @Html.ActionLink("Create New", "Create")
    </div>
    <div class="col-md-2">

    </div>
    @Html.ActionLink("Export", "ExportToExcel")
</div>







<div ng-app="DemandApp" ng-controller="customersCtrl">
    <table class="table" ng-table ="usersTable" show-filter=true>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)


            </th>
            <th>
                @Html.DisplayNameFor(model => model.DemandNumber)
                <input type="text" ng-model="searchNumber" ng-change="filter()" class="form-control input-sm" />
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SubmissionDate)
                <input type="text" ng-model="searchDate" ng-change="filter()" class="form-control input-sm " />
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DemandDesc)
                <input type="text" ng-model="searchDesc" ng-change="filter()" class="form-control input-sm "/>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Priority)

                <select ng-model="selectedPriority" ng-change="filter()" class="form-control input-sm">
                    <option value="" selected="selected"> All</option>
                    <option ng-repeat="x in names" value="{{x.Priority}}">{{x | Priority}}</option>
                </select>

            </th>
            <th>
                @Html.DisplayNameFor(model => model.DemandStatus)
                <select ng-model="selectedStatus" ng-change="filter()" class="form-control input-sm">
                    <option value="" selected="selected"> All</option>
                    <option ng-repeat="x in Status" value="{{x.DemandStatus}}">{{x | DemandStatus}}</option>
                </select>

            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phase)

                <select ng-model="selectedPhase" ng-change="filter()" class="form-control input-sm">
                    <option value="" selected="selected"> All</option>
                    <option ng-repeat="x in Phase" value="{{x.Phase}}">{{x | Phase}}</option>
                </select>

            </th>

        </tr>
        <tr ng-repeat="x in filteredList  | filter   ">

            <td>

                {{ x.Id }}

            </td>

            <td>
                <a href="@Url.Action("Details" , "Demands")/{{x.Id}}">

                    {{ x.DemandNumber }}
                </a>
            </td>
            <td>{{ x.SubmissionDate }}</td>
            <td>{{ x.DemandDesc }}</td>
            <td>{{ x | Priority }}</td>
            <td>{{ x | DemandStatus }}</td>
            <td>{{ x | Phase }}</td>

        </tr>
    </table>
</div>
<script>
        var app = angular.module('DemandApp', []);


        app.filter('Priority', function () {

            return function (x) {
                switch (x.Priority) {

                    case 0 :
                        return "High";

                    case 1:
                        return "Medium";

                    case 2:
                        return "low";

                    default:
                        return " ";
                }
            };
        });


        app.filter('DemandStatus', function () {

            return function (x) {

                switch (x.DemandStatus) {
                    case 0:
                        return "Completed";
                    case 1:
                        return "Assigned";
                    case 2:
                        return "Rejected";

                    case 3:
                        return "Cancelled";

                    case 4:
                        return "onHold";


                    default:
                        return "onHold";
                }
            };
        });


        app.filter('Phase', function () {

            return function (x) {

                switch (x.Phase) {
                    case 0:
                        return "Initial Review";
                    case 1:
                        return "Pre Assessment Validation";
                    case 2:
                        return "High Level Assessment";

                    case 3:
                        return "Business Approval";

                    case 4:
                        return "Awaiting Delivery";

                    case 5:
                        return "In Delivery";


                    default:
                        return " ";

                }
            };
        });



        app.controller('customersCtrl', function ($scope, $http  , $filter) {
            $http.get("@Url.Action("IndexData", "Demands")")
                .then(function (response) {$scope.filteredList = $scope.list = JSON.parse(response.data); });

            //$scope.orderByMe = function (x) {
            //    $scope.myOrderBy = x;
            //}
            $scope.selectedPriority = "";
            $scope.names = [{ Priority: 0 }, { Priority: 1 }, { Priority: 2 } ];

            $scope.selectedStatus = "";
            $scope.Status = [{ DemandStatus: 0 }, { DemandStatus: 1 }, { DemandStatus: 2 }, { DemandStatus: 3 }, { DemandStatus: 4 }];
            $scope.selectedPhase = "";
            $scope.Phase = [{ Phase: 0 }, { Phase: 1 }, { Phase: 2 }, { Phase: 3 }, { Phase: 4 }, { Phase:5 }]
            $scope.filteredList = [];
            //$scope.filter = () => {
            //    $scope.filteredList = $scope.list.filter(item => item.Priority == $scope.selectedPriority );

            //}
            
            $scope.searchNumber = "";
            $scope.searchDate = "";
            $scope.searchDesc = "";
            $scope.filter = () => {
                $scope.filteredList = $scope.list.filter(item => (($scope.selectedPriority == "") || item.Priority == $scope.selectedPriority)
                                                              && (($scope.selectedStatus == "") || item.DemandStatus == $scope.selectedStatus)
                    && (($scope.selectedPhase == "") || item.Phase == $scope.selectedPhase)
                    && (($scope.searchNumber === "") || (item.DemandNumber + "").includes($scope.searchNumber))
                    && (($scope.searchDate == "") || (item.SubmissionDate + "").includes($scope.searchDate))
                    && (($scope.searchDesc === "") || (item.DemandDesc + "").includes($scope.searchDesc))
                    );
                    
            }
     


        });




</script>